#!/usr/bin/bash


echo 'all: build up'
echo ''
# echo 'setup:'
# echo '	@echo "Setting up the volumes folders..."'
# echo '	@if [ ! -d ~/data/web ]; then mkdir -p ~/data/web; fi'
# echo '	@if [ ! -d ~/data/mariadb ]; then mkdir -p ~/data/mariadb; fi'
# echo ''
echo 'down:'
echo '	@echo "Stopping and removing containers, networks, volumes, and images..."'
echo '	docker compose -f srcs/docker-compose.yml down'
echo ''
echo 'build:'
echo '	@echo "Building Docker images without cache..."'
echo '	docker compose -f srcs/docker-compose.yml build --no-cache'
echo ''
echo 'up: build'
echo '	@echo "Starting containers in detached mode..."'
echo '	docker compose -f srcs/docker-compose.yml up'
echo ''
echo 'clean: kill'
echo '	@echo "Pruning Docker system to remove all unused data..."'
echo '	docker system prune -a --volumes -f'
echo ''
echo 'st:'
echo '	@echo "Listing Docker images and running containers..."'
echo '	docker images'
echo '	docker ps'
echo ''
echo 'kill:'
echo '	@echo "Killing all running containers..."'
echo '	docker compose -f srcs/docker-compose.yml down --rmi all --volumes --remove-orphans'
echo ''
echo 're: down kill clean all'
echo ''
echo 'help:'
echo '	@echo "Showing help information..."'
echo '	@echo "Available commands:"'
echo '	@echo "  all    - Build, start, and attach to containers"'
echo '	@echo "  down   - Stop and remove containers, networks, volumes, and images"'
echo '	@echo "  clean  - Remove all stopped containers, unused networks, and dangling images"'
echo '	@echo "  re     - Restart the entire application"'
echo '	@echo "  st     - Show the status of the application"'
echo '	@echo "  kill   - Stop and remove all containers"'
echo '	@echo "  help   - Show this help message"'
echo ''
echo '.PHONY: all down clean re st help setup'

